// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyeaxhwuyiqwzmbegmzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZWF4aHd1eWlxd3ptYmVnbXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODU5NjgsImV4cCI6MjA2NzI2MTk2OH0.m3Dz6P7D6NDk-tUIJJnn_KoObl1j12OVwhBmPuIYkUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});